"""Prospective alternate-action diagnostic in executed MuJoCo branches.

Every branch independently resets and replays exactly the same stored action
prefix. Three observations warm each frozen model; then all nine five-step
action sequences are forecast without updating history. Outcomes are measured
by the simulator, never generated by the learned model. Diagnostic outcomes
must not select checkpoints, controller gains, or primary evaluation seeds.

This probes local action effects around one prefix policy. Five-step selection
regret is a local diagnostic, not long-horizon lifting or closed-loop safety.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import json
from pathlib import Path
import platform
import subprocess
import sys
import time

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = ROOT/'outputs/revision_v2/counterfactual'
PREFIX_STEPS = (44, 78, 112)
HORIZON = 5
Z_OFFSETS = (-.06, 0., .06)
GRIP_OFFSETS = (-.10, 0., .10)
CENTER = 4
FORCE_BUDGET = 8.
TARGET_HEIGHT = .10


def sha256(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def native(value):
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, np.generic):
        return value.item()
    raise TypeError(type(value).__name__)


def runtime_provenance(model_python, device):
    """Probe the actual model runtime without changing model weights or actions.

    The same interpreter and requested device are passed to every bridge. The
    empty tensor checks the resolved torch device. CPU inference does not create
    any CUDA context; torch.version.cuda below describes the installed build.
    """
    code = '''import json, platform, sys, numpy, torch
torch.set_num_threads(4)
device = torch.empty(0, device=sys.argv[1]).device
print(json.dumps({"python_executable":sys.executable,"python_version":sys.version,
 "torch_version":torch.__version__,"numpy_version":numpy.__version__,
 "requested_device":sys.argv[1],"resolved_device":str(device),
 "torch_num_threads":torch.get_num_threads(),"cuda_build_version":torch.version.cuda,
 "accelerator_name":torch.cuda.get_device_name(device) if device.type=="cuda" else None,
 "machine":platform.machine(),"processor":platform.processor()}))'''
    result = subprocess.run([str(model_python), '-c', code, device],
        capture_output=True, text=True, check=True,
        creationflags=getattr(subprocess, 'CREATE_NO_WINDOW', 0))
    return {'simulator_python_executable':sys.executable,
            'simulator_python_version':sys.version, 'simulator_numpy_version':np.__version__,
            'platform':platform.platform(), 'machine':platform.machine(),
            'model_inference':json.loads(result.stdout)}


class ForecastBridge:
    def __init__(self, python, checkpoint, device, log_path):
        self.log = Path(log_path).open('w', encoding='utf-8')
        self.process = subprocess.Popen([str(python), str(Path(__file__).with_name('adaptive_controller.py')),
            '--model', str(checkpoint), '--mode', 'model_guard', '--device', device],
            stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=self.log,
            text=True, bufsize=1, creationflags=getattr(subprocess, 'CREATE_NO_WINDOW', 0))
        try:
            self.metadata = self._read()
            if not self.metadata.get('ready'):
                raise RuntimeError('Model bridge did not become ready.')
        except BaseException:
            self.close()
            raise

    def _read(self):
        line = self.process.stdout.readline()
        if not line:
            raise RuntimeError('Model bridge stopped; inspect its stderr log.')
        result = json.loads(line)
        if 'error' in result:
            raise RuntimeError(result['error'])
        return result

    def request(self, request):
        self.process.stdin.write(json.dumps(request, allow_nan=False)+'\n')
        self.process.stdin.flush()
        return self._read()

    def forecast(self, history, actions):
        self.request({'command': 'reset'})
        for observation in history:
            self.request({'rgb_base64': base64.b64encode(observation['rgb'].tobytes()).decode('ascii'),
                'tactile': observation['tactile'].tolist(), 'proprio': observation['proprio'].tolist(),
                'control_active': False})
        result = self.request({'command': 'forecast', 'actions': actions.tolist()})
        if not np.array_equal(np.asarray(result['actions'], np.float32), actions):
            raise AssertionError('The model did not forecast exactly the supplied branch actions.')
        return result

    def close(self):
        if self.process.poll() is None:
            try:
                self.process.stdin.write('{"command":"quit"}\n')
                self.process.stdin.flush()
                self.process.wait(timeout=15)
            except (BrokenPipeError, OSError, subprocess.TimeoutExpired):
                self.process.terminate()
                self.process.wait(timeout=15)
        self.log.close()


def prefix_action(env, observation, step):
    # Exactly the force-feedback collection policy after the common approach.
    action = env.script_action()
    if 44 <= step < 135:
        action[[0, 1, 3, 4, 5]] = 0.
        action[6] = np.clip(.12*(5.-float(observation['tactile'][[0, 3]].mean())), -.25, .35)
    return action.astype(np.float32)


def candidate_actions(base):
    actions = np.zeros((9, HORIZON, 7), np.float32)
    for index, (dz, dg) in enumerate((z, g) for z in Z_OFFSETS for g in GRIP_OFFSETS):
        actions[index, :, 2] = np.clip(float(base[2])+dz, -.6, .6)
        actions[index, :, 6] = np.clip(float(base[6])+dg, -.25, .35)
    return actions


def copy_state(state):
    return {key: value.copy() if isinstance(value, np.ndarray) else value for key, value in state.items()}


def prefix_difference(reference_history, history, reference_state, state):
    """Verify reproducibility; the stored partial state is NEVER restored."""
    diffs = []
    if len(history) != 3:
        raise AssertionError('A branch must have three actual pre-action observations.')
    for reference, current in zip(reference_history, history):
        if not np.array_equal(reference['rgb'], current['rgb']):
            raise AssertionError('Reset/replayed RGB differs from the reference prefix.')
        for key in ('tactile', 'proprio', 'height', 'substep_normal_peak'):
            diffs.append(float(np.max(np.abs(reference[key]-current[key]))))
    for key in reference_state:
        value = np.asarray(reference_state[key], float)-np.asarray(state[key], float)
        if value.size:
            diffs.append(float(np.abs(value).max()))
    maximum = max(diffs, default=0.)
    if maximum > 1e-7:
        raise AssertionError(f'Independent prefix replay differs by {maximum}; outcomes cannot be paired.')
    return maximum


def collect_environment(env, row, prefixes, bridges, out, metadata):
    observation = env.reset(row['seed'], row['params'])
    observations = [observation]
    actions = []
    reference = {}
    # One extra action is evaluated at the final prefix to define its grid.
    for step in range(max(prefixes)+1):
        if step in prefixes:
            reference[step] = {'history': observations[-3:], 'state': copy_state(env.get_state())}
        action = prefix_action(env, observation, step)
        if step in prefixes:
            reference[step]['base_action'] = action.copy()
        if step == max(prefixes):
            break
        observation, _, _, _ = env.step(action)
        actions.append(action.copy())
        observations.append(observation)
    prefix_actions = np.stack(actions)
    actual_height, actual_peak, actual_touch, actual_reward = [], [], [], []
    candidates, replay_errors, initial_height, initial_touch, initial_peak = [], [], [], [], []
    model_forecasts = []
    initial_prefix_peak = []
    for step in prefixes:
        reference_step = reference[step]
        candidate = candidate_actions(reference_step['base_action'])
        candidates.append(candidate)
        initial = reference_step['history'][-1]
        initial_height.append(initial['height'][0])
        initial_touch.append(initial['tactile'])
        initial_peak.append(initial['substep_normal_peak'])
        initial_prefix_peak.append(np.max(np.stack([obs['substep_normal_peak'] for obs in observations[:step+1]]), axis=0))
        # Predictions are frozen before any alternate branch is executed.
        model_forecasts.append([bridge.forecast(reference_step['history'], candidate) for bridge in bridges])
        heights, peaks, touches, rewards, errors = [], [], [], [], []
        for branch, branch_actions in enumerate(candidate):
            obs = env.reset(row['seed'], row['params'])
            history = [obs]
            for prefix_index in range(step):
                # Read-only action generation also reproduces the adapter RNG
                # stream; the cached action is authoritative for all branches.
                env.script_action()
                obs, _, _, _ = env.step(prefix_actions[prefix_index])
                history.append(obs)
                history = history[-3:]
            errors.append(prefix_difference(reference_step['history'], history,
                                            reference_step['state'], env.get_state()))
            branch_states, branch_rewards = [], []
            for action in branch_actions:
                obs, reward, _, info = env.step(action)
                if info['substeps'] != 25:
                    raise AssertionError('Expected 25 physical substeps per observed control interval.')
                branch_states.append(obs)
                branch_rewards.append(reward)
            heights.append([state['height'][0] for state in branch_states])
            peaks.append([state['substep_normal_peak'] for state in branch_states])
            touches.append([state['tactile'] for state in branch_states])
            rewards.append(branch_rewards)
        actual_height.append(heights)
        actual_peak.append(peaks)
        actual_touch.append(touches)
        actual_reward.append(rewards)
        replay_errors.append(errors)
        print(json.dumps({'seed':row['seed'], 'prefix':step, 'branches':9,
                          'prefix_replay_max_difference':max(errors)}), flush=True)
    arrays = dict(seed=np.array(row['seed']), prefixes=np.asarray(prefixes),
                  prefix_actions=prefix_actions, candidate_actions=np.asarray(candidates),
                  actual_height_m=np.asarray(actual_height), actual_peak_N=np.asarray(actual_peak),
                  actual_tactile_N=np.asarray(actual_touch), actual_native_reward=np.asarray(actual_reward),
                  initial_height_m=np.asarray(initial_height), initial_tactile_N=np.asarray(initial_touch),
                  initial_peak_N=np.asarray(initial_peak), prefix_max_peak_N=np.asarray(initial_prefix_peak),
                  replay_max_difference=np.asarray(replay_errors),
                  params_json=np.array(json.dumps(env.params, sort_keys=True)),
                  run_metadata_json=np.array(json.dumps(metadata, sort_keys=True)),
                  model_seed=np.asarray(metadata['model_seeds']),
                  model_variant=np.asarray(metadata['model_variants']))
    # Array order is [modality/model seed, prefix state, branch, horizon, channel].
    for key in ('raw_peak_N', 'anchored_peak_N', 'raw_tactile_N', 'anchored_tactile_N', 'height_m',
                'native_reward', 'current_decoded_normal_N', 'measured_normal_N', 'force_anchor_offset_N'):
        arrays['pred_'+key] = np.asarray([[state[model_index][key] for state in model_forecasts]
                                        for model_index in range(len(bridges))])
    target = out/f'environment_{row["seed"]}.npz'
    np.savez_compressed(target, **arrays)
    return target


def mean(values):
    values = np.asarray(values, float)
    valid = np.isfinite(values)
    return float(values[valid].mean()) if valid.any() else None


def midranks(values):
    values = np.asarray(values, float)
    order = np.argsort(values, kind='stable')
    ranks = np.empty(len(values), float)
    position = 0
    while position < len(values):
        stop = position+1
        while stop < len(values) and values[order[stop]] == values[order[position]]:
            stop += 1
        ranks[order[position:stop]] = .5*(position+stop-1)
        position = stop
    return ranks


def rank_correlation(prediction, actual):
    prediction, actual = midranks(prediction), midranks(actual)
    prediction -= prediction.mean()
    actual -= actual.mean()
    denominator = np.linalg.norm(prediction)*np.linalg.norm(actual)
    # A constant predictor's ordering is undefined, not evidence of zero error.
    return float(prediction@actual/denominator) if denominator > 0 else np.nan


def constrained_selection(pred_height, pred_peak):
    worst = pred_peak.max(axis=(1, 2))
    feasible = worst <= FORCE_BUDGET
    utility = np.clip(pred_height[:, -1]/TARGET_HEIGHT, 0, 1)
    # Central action wins exact ties, then ascending branch index.
    order = [CENTER]+[i for i in range(len(worst)) if i != CENTER]
    if feasible.any():
        valid = [index for index in order if feasible[index]]
        return max(valid, key=lambda index: utility[index]), False
    return min(order, key=lambda index: worst[index]), True


def method_metrics(actual_height, actual_peak, actual_tactile, pred_height, pred_peak, pred_tactile):
    result = {
        'height_MAE_m': float(np.abs(pred_height-actual_height).mean()),
        'terminal_height_MAE_m': float(np.abs(pred_height[..., -1]-actual_height[..., -1]).mean()),
        'interval_peak_MAE_N': float(np.abs(pred_peak-actual_peak).mean()),
        'tactile_MAE_N': float(np.abs(pred_tactile-actual_tactile).mean()),
        'normal_tactile_MAE_N': float(np.abs(pred_tactile[..., [0,3]]-actual_tactile[..., [0,3]]).mean()),
    }
    noncenter = [index for index in range(9) if index != CENTER]
    for name, pred, actual in [('height', pred_height, actual_height), ('interval_peak', pred_peak, actual_peak),
                               ('tactile', pred_tactile, actual_tactile)]:
        pred_effect = pred[:, noncenter]-pred[:, CENTER:CENTER+1]
        actual_effect = actual[:, noncenter]-actual[:, CENTER:CENTER+1]
        unit = 'm' if name == 'height' else 'N'
        result[f'action_effect_{name}_MAE_{unit}'] = float(np.abs(pred_effect-actual_effect).mean())
    height_ranks, peak_ranks, regret, violations, selected_height, fallback, oracle_values = [], [], [], [], [], [], []
    for state in range(len(actual_height)):
        ah, ap = actual_height[state], actual_peak[state]
        ph, pp = pred_height[state], pred_peak[state]
        height_ranks.append(rank_correlation(ph[:, -1], ah[:, -1]))
        peak_ranks.append(rank_correlation(pp.max(axis=(1, 2)), ap.max(axis=(1, 2))))
        selected, no_feasible = constrained_selection(ph, pp)
        actual_violation = ap.max(axis=(1, 2)) > FORCE_BUDGET
        actual_utility = np.where(actual_violation, 0., np.clip(ah[:, -1]/TARGET_HEIGHT, 0, 1))
        oracle = float(actual_utility.max())
        regret.append(oracle-float(actual_utility[selected]))
        violations.append(actual_violation[selected])
        selected_height.append(ah[selected, -1])
        fallback.append(no_feasible)
        oracle_values.append(oracle)
    result.update(terminal_height_rank_correlation=mean(height_ranks),
        peak_rank_correlation=mean(peak_ranks),
        terminal_height_rank_defined_fraction=float(np.isfinite(height_ranks).mean()),
        peak_rank_defined_fraction=float(np.isfinite(peak_ranks).mean()),
        constraint_aware_selection_regret=float(np.mean(regret)),
        selected_force_violation_rate=float(np.mean(violations)),
        selected_terminal_height_m=float(np.mean(selected_height)),
        no_predicted_feasible_candidate_fraction=float(np.mean(fallback)),
        oracle_constraint_aware_utility=float(np.mean(oracle_values)))
    return result


def analyze_environment(path):
    with np.load(path, allow_pickle=False) as episode:
        actual_h, actual_p, actual_t = [episode[key] for key in ('actual_height_m','actual_peak_N','actual_tactile_N')]
        h = np.broadcast_to(episode['initial_height_m'][:, None, None], actual_h.shape)
        t = np.broadcast_to(episode['initial_tactile_N'][:, None, None, :], actual_t.shape)
        interval_p = np.broadcast_to(episode['initial_peak_N'][:, None, None, :], actual_p.shape)
        normal_p = np.broadcast_to(episode['initial_tactile_N'][:, None, None, [0, 3]], actual_p.shape)
        methods = {
            'persistence': method_metrics(actual_h, actual_p, actual_t, h, interval_p, t),
            'normal_force_persistence': method_metrics(actual_h, actual_p, actual_t, h, normal_p, t)}
        model_variants = episode['model_variant'].tolist() if 'model_variant' in episode else ['visuotactile']*len(episode['model_seed'])
        for model_index, (modality, seed) in enumerate(zip(model_variants, episode['model_seed'])):
            for variant in ('raw', 'anchored'):
                methods[f'wm_{modality}_{variant}_seed{int(seed)}'] = method_metrics(actual_h, actual_p, actual_t,
                    episode['pred_height_m'][model_index], episode[f'pred_{variant}_peak_N'][model_index],
                    episode[f'pred_{variant}_tactile_N'][model_index])
        # Average model seeds within each independent environment first.
        for modality in sorted(set(model_variants)):
            for variant in ('raw', 'anchored'):
                members = [metrics for key, metrics in methods.items() if key.startswith(f'wm_{modality}_{variant}_seed')]
                methods[f'wm_{modality}_{variant}'] = {key:mean([m[key] if m[key] is not None else np.nan for m in members]) for key in members[0]}
                compared = methods[f'wm_{modality}_{variant}']
                for baseline in ('persistence', 'normal_force_persistence'):
                    base = methods[baseline]
                    methods[f'paired_wm_{modality}_{variant}_minus_{baseline}'] = {
                        key:compared[key]-base[key] if compared[key] is not None and base[key] is not None else None
                        for key in base}
        if {'vision', 'visuotactile'}.issubset(set(model_variants)):
            for variant in ('raw', 'anchored'):
                base, compared = methods[f'wm_vision_{variant}'], methods[f'wm_visuotactile_{variant}']
                methods[f'paired_visuotactile_minus_vision_{variant}'] = {
                    key:compared[key]-base[key] if compared[key] is not None and base[key] is not None else None
                    for key in base}
        actions = episode['candidate_actions']
        unique_counts = [len(np.unique(state.reshape(9, -1), axis=0)) for state in actions]
        return {'seed':int(episode['seed']), 'prefix_steps':episode['prefixes'].tolist(),
                'unique_candidates_per_prefix':unique_counts,
                'prefix_replay_max_difference':float(episode['replay_max_difference'].max()),
                'actual_action_effect_height_mean_abs_m':float(np.abs(actual_h[:, [i for i in range(9) if i != CENTER]]-actual_h[:, CENTER:CENTER+1]).mean()),
                'actual_action_effect_peak_mean_abs_N':float(np.abs(actual_p[:, [i for i in range(9) if i != CENTER]]-actual_p[:, CENTER:CENTER+1]).mean()),
                'methods':methods}


def bootstrap_environment_metrics(rows, resamples=2000, seed=20401010):
    rng = np.random.default_rng(seed)
    n = len(rows)
    indices = rng.integers(0, n, size=(resamples, n))
    summary = {}
    for method in rows[0]['methods']:
        summary[method] = {}
        for metric in rows[0]['methods'][method]:
            values = np.array([row['methods'][method][metric] if row['methods'][method][metric] is not None else np.nan for row in rows])
            samples = values[indices]
            counts = np.isfinite(samples).sum(axis=1)
            means = np.divide(np.nansum(samples, axis=1), counts,
                              out=np.full(resamples, np.nan), where=counts > 0)
            finite = means[np.isfinite(means)]
            interval = np.quantile(finite, [.025, .975]).tolist() if len(finite) else [None, None]
            summary[method][metric] = {'mean':mean(values), 'ci95_environment_bootstrap':interval,
                                      'environments_with_defined_value':int(np.isfinite(values).sum())}
    return summary


def analyze(out, expected_seeds, resamples, bootstrap_seed, smoke):
    rows = []
    for seed in expected_seeds:
        path = out/f'environment_{seed}.npz'
        if not path.exists():
            raise FileNotFoundError(f'Missing prespecified environment: {path}')
        rows.append(analyze_environment(path))
    (out/'per_environment_metrics.jsonl').write_text('\n'.join(json.dumps(row, allow_nan=False) for row in rows)+'\n')
    summary = {
        'kind':'validation-only implementation smoke' if smoke else 'held-out counterfactual action diagnostic',
        'environment_count':len(rows), 'environment_seeds':expected_seeds,
        'state_count':sum(len(row['prefix_steps']) for row in rows),
        'branch_count':sum(9*len(row['prefix_steps']) for row in rows),
        'independent_statistical_unit':'environment; model seeds, prefixes, actions, horizons and fingers are nested repeated observations',
        'bootstrap_resamples':resamples, 'bootstrap_seed':bootstrap_seed,
        'run_manifest_sha256':sha256(out/'run_manifest.json'),
        'device':json.loads((out/'run_manifest.json').read_text()).get('device', 'unrecorded_legacy_run'),
        'runtime_provenance':json.loads((out/'run_manifest.json').read_text()).get('runtime_provenance'),
        'metrics':bootstrap_environment_metrics(rows, resamples, bootstrap_seed),
        'definitions':{
            'persistence':'Current tactile and height held constant; previous measured interval peak held constant.',
            'normal_force_persistence':'Same, except peak forecast holds current endpoint normal force constant.',
            'action_effect':'Predicted and actual candidate-minus-center differences, center index4 excluded from the averaged error; all5horizons retained.',
            'rank':'Spearman correlation with exact midranks for ties; constant rankings are undefined, reported with defined fraction.',
            'selection':'Among predicted peak<=8N candidates maximize clipped terminal height/0.10; exactties choosecenter thenindex. Ifnone predictedfeasible chooseminimum predictedpeak.',
            'regret':'Oracle minus selected executed utility over9branches; utility=clip(terminalheight/.10,0,1) if all branchsubsteps peak<=8N else0. Prefix forces are excluded from this local diagnostic.',
            'paired_difference':'Model metric minus each named persistence baseline within each environment, then bootstrap whole environments. Both previous-interval-peak and current-endpoint-normal baselines are retained.',
            'branching':'Everybranch independently reset and replayed; no partial-state restoration.'},
        'limitations':['Local five-step decisions do not measure sustained lifting or closed-loop safety.',
                      'Diagnostic prefix policy uses common privileged scripted approach/vertical reference; learned model sees only RGB,tactile,proprio.',
                      'Vision raw forecasts exclude tactile input; vision anchored forecasts additionally use the identical measured-tactile offset correction, so they are not vision-only predictions.',
                      'Averaging over fixed clipping duplicates is retained by protocol; unique candidate counts are reported.',
                      'Rank means are conditional on defined rankings; see defined fractions.',
                      'Diagnostic outcomes must not tune model weights, gains, or choose primary evaluation cohorts.'],
        'max_prefix_replay_difference':max(row['prefix_replay_max_difference'] for row in rows),
        'unique_candidates_per_environment':[row['unique_candidates_per_prefix'] for row in rows]}
    (out/'summary.json').write_text(json.dumps(summary, indent=2, allow_nan=False))
    print(json.dumps({'analysis_complete':str(out/'summary.json'), 'environments':len(rows),
                      'branches':summary['branch_count']}), flush=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--protocol', type=Path, default=ROOT/'outputs/revision_v2/protocol.json')
    parser.add_argument('--model-root', type=Path, default=ROOT/'outputs/revision_v2/world_models')
    parser.add_argument('--out', type=Path, default=DEFAULT_OUT)
    parser.add_argument('--gpu-python', required=True)
    parser.add_argument('--device', choices=('cpu', 'cuda'), default='cuda',
                        help='Inference device for all frozen forecast models; recorded in every run/episode. Use cpu to avoid concurrent CUDA contexts.')
    parser.add_argument('--resume', action='store_true')
    parser.add_argument('--analyze-only', action='store_true')
    parser.add_argument('--smoke', action='store_true', help='One validation environment, prefix44, both modalities seed0; never primary diagnostic rows.')
    args = parser.parse_args()
    plan = json.loads(args.protocol.read_text())
    if args.smoke:
        rows = [next(row for row in plan['collection'] if row['split'] == 'val')]
        prefixes, training_seeds = [44], [0]
        if args.out == DEFAULT_OUT:
            parser.error('Smoke must use a separate --out directory.')
    else:
        rows, prefixes, training_seeds = plan['counterfactual'], list(PREFIX_STEPS), plan['training_seeds']
    if len({row['seed'] for row in rows}) != len(rows):
        raise ValueError('Duplicate environment seeds.')
    args.out.mkdir(parents=True, exist_ok=True)
    model_specs = [(modality, seed) for modality in ('vision', 'visuotactile') for seed in training_seeds]
    checkpoints = [args.model_root/f'{modality}_seed{seed}'/'best.pt' for modality, seed in model_specs]
    metadata = {'protocol_sha256':sha256(args.protocol), 'source_sha256':sha256(__file__),
        'adaptive_controller_sha256':sha256(Path(__file__).with_name('adaptive_controller.py')),
        'adapter_sha256':sha256(Path(__file__).with_name('sim_adapter_v2.py')),
        'model_sha256':[sha256(path) for path in checkpoints],
        'model_seeds':[seed for modality, seed in model_specs],
        'model_variants':[modality for modality, seed in model_specs],
        'environment_seeds':[row['seed'] for row in rows], 'prefixes':prefixes,
        'horizon':HORIZON, 'z_offsets':list(Z_OFFSETS), 'grip_offsets':list(GRIP_OFFSETS),
        'center_index':CENTER, 'smoke':args.smoke,
        'device':args.device}
    manifest = args.out/'run_manifest.json'
    if args.analyze_only:
        if not manifest.exists():
            raise FileNotFoundError('Analysis requires the frozen run manifest.')
        stored = json.loads(manifest.read_text())
        for key, value in metadata.items():
            if stored.get(key) != value:
                raise ValueError(f'Analysis inputs differ from frozen run: {key}')
        # Analysis may use ordinary Python; preserve the execution runtime record.
        metadata = stored
    else:
        metadata['runtime_provenance'] = runtime_provenance(args.gpu_python, args.device)
    if manifest.exists():
        if json.loads(manifest.read_text()) != metadata:
            raise ValueError('Run manifest differs from frozen source/checkpoints/protocol; use a separate output.')
        if not args.resume and not args.analyze_only:
            raise FileExistsError('Existing run: use --resume explicitly.')
    else:
        if args.analyze_only:
            raise FileNotFoundError('Analysis requires the frozen run manifest.')
        manifest.write_text(json.dumps(metadata, indent=2))
    if not args.analyze_only:
        # Import only for simulator execution; metrics can run in ordinary Python.
        from sim_adapter_v2 import SimAdapterV2
        bridges, env = [], None
        started = time.time()
        try:
            for (modality, seed), checkpoint in zip(model_specs, checkpoints):
                bridges.append(ForecastBridge(args.gpu_python, checkpoint, args.device, args.out/f'{modality}_seed{seed}_stderr.log'))
            env = SimAdapterV2(render=True)
            import mujoco
            import robosuite
            runtime_record = {'device':args.device, 'runtime_provenance':metadata['runtime_provenance'],
                'mujoco_version':mujoco.__version__, 'robosuite_version':robosuite.__version__,
                'bridges':[bridge.metadata for bridge in bridges],
                'manifest_sha256':sha256(manifest)}
            (args.out/'runtime_provenance.json').write_text(json.dumps(runtime_record, indent=2))
            for row in rows:
                target = args.out/f'environment_{row["seed"]}.npz'
                if target.exists():
                    with np.load(target, allow_pickle=False) as old:
                        if json.loads(str(old['run_metadata_json'])) != metadata:
                            raise ValueError('Existing environment belongs to another run.')
                        if old['actual_height_m'].shape != (len(prefixes), 9, HORIZON):
                            raise ValueError('Incomplete environment arrays.')
                    continue
                target = collect_environment(env, row, prefixes, bridges, args.out, metadata)
                with (args.out/'completed.jsonl').open('a') as log:
                    log.write(json.dumps({'seed':row['seed'], 'path':target.name, 'sha256':sha256(target),
                                          'elapsed_seconds':time.time()-started})+'\n')
        finally:
            if env is not None:
                env.close()
            for bridge in bridges:
                bridge.close()
    analyze(args.out, metadata['environment_seeds'], plan['bootstrap_resamples'], plan['bootstrap_seed'], args.smoke)


if __name__ == '__main__':
    main()
